services:
  pg18:
    image: ghcr.io/djoongaar/postgres:16-bookworm
    container_name: pg18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=ru-RU
  # PostgreSQL V16.13 for 1C
  pg16_1c:
    image: ghcr.io/djoongaar/postgres:V16-1c
    container_name: pg16_1c
    build:
      context: "16-1c"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=ru-RU
    restart: unless-stopped
  # PostgreSQL V18.3 for 1C
  pg18_1c:
    image: ghcr.io/djoongaar/postgres:V18-1c
    container_name: pg18_1c
    build:
      context: "18-1c"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=ru-RU
    restart: unless-stopped
  # Oracle 11g Express edition
  oracle_11g:
    image: oracleinanutshell/oracle-xe-11g:latest
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_DISABLE_ASYNCH_IO: true
      ORACLE_ENABLE_XDB: true
    ports:
      - 1521:1521
