services:

  postgrespro16_1c:
    image: postgrespro16_1c:V16.13
    build:
      context: "postgrespro16-1c"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 15432:5432
    restart: unless-stopped

  postgrespro18_1c:
    image: postgrespro18_1c
    build:
      context: "postgrespro18-1c"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 25432:5432
    restart: unless-stopped