listen_addresses = '*'
shared_buffers = 1GB                    # min 128kB
dynamic_shared_memory_type = posix      # the default is usually the first option
max_wal_size = 10GB
min_wal_size = 80MB
datestyle = 'iso, mdy'
timezone = 'Europe/Moscow'
max_connections = 3000
max_wal_senders = 14
wal_level = 'logical'
checkpoint_timeout = 60min

#Logs
log_timezone = 'Europe/Moscow'
log_line_prefix='%u@%h [%p] %d %t: '
log_destination = 'stderr'
log_hostname = on
log_connections = on
